title: BillParkerMapping.com
author: Bill Parker
email: parkerw13@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This blog will showcase some of my skills in Python in ArcPy and
  some new ones using Python with PostGIS as I learn them. It will
  also be a place for me to display web maps as I learn how to create
  them and work on learning JavaScript


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  parkerw13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
